name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Create SSH Key Temp File
        run: |
          # Write the private key from the secret to a temporary file
          echo "${{ secrets.SERVERKEY }}" > private_key
          # Secure the key file
          chmod 600 private_key

      - name: Build, publish, and deploy
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y openssh-client
          dotnet publish Darknote.API -c Release 
          scp -o StrictHostKeyChecking=no -i private_key -P ${{ secrets.SERVERPORT }} -r ${{ github.workspace }}/Darknote.API/bin/Release/net9.0/publish/* ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }}:/var/www/darknote      
          ssh -o StrictHostKeyChecking=no -i private_key -p ${{ secrets.SERVERPORT }} ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }} "sudo systemctl restart kestrel-darknote.service"
          ssh -o StrictHostKeyChecking=no -i private_key -p ${{ secrets.SERVERPORT }} ${{ secrets.SERVERUSERNAME }}@${{ secrets.SERVERADDRESS }} "sudo systemctl restart nginx"

      - name: Cleanup SSH Key
        run: |
          # Remove the key file after use
          rm -f private_key
